christmas_gifts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gifts.urls')),
]

gifts/urls.py
from django.urls import path

from . import views

app_name = "gifts"
urlpatterns = [
    path('', views.ListPersons.as_view(), name='listPersons'),
    path('person/create', views.AddPerson.as_view(), name='addPerson'),
    path('person/<int:pk>/delete', views.DeletePerson.as_view(), name='deletePerson'),
    path('person/<int:pk>/update', views.UpdatePerson.as_view(), name='updatePerson'),    
    path('person/<int:pk>', views.DetailPerson.as_view(), name='detailPerson'),
    path('gift/add/<int:person>', views.AddGift.as_view(), name="addGift"),
    path('gift/<int:pk>/update', views.UpdateGift.as_view(), name='updateGift'),
    path('gift/<int:pk>/delete', views.DeleteGift.as_view(), name='deleteGift'),
    #path('gift/<int:pk>/setWrapped/<int:b>', views.SetGiftWrapped.as_view(), name='setGiftWrapped'),
]

gifts/models.py
from django.db import models


class Person(models.Model):

    name = models.CharField(max_length=200)
    budget = models.DecimalField(max_digits=50, decimal_places=2)

    def __str__(self):
        return self.name


class Gift(models.Model):

    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    bought = models.BooleanField(default=False)
    wrapped = models.BooleanField(default=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

gifts/views.py
from django.views import generic
from .models import Person, Gift

from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import FormMixin
from django.forms import modelformset_factory, inlineformset_factory


class ListPersons(generic.ListView):
    model = Person
    # context_object_name = 'persons'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        persons = context["object_list"]
        new_context = {}
        budget_total = 0
        spent = 0
        budget_used = 0
        for person in persons:
            tmp = {
                'instance': person,
                'bought': person.gift_set.filter(bought=True).count(),
                'wrapped': person.gift_set.filter(wrapped=True).count(),
                'total': person.gift_set.count()
            }
            new_context[person.id] = tmp
            budget_total += person.budget

            gifts = person.gift_set.all()
            total_gifts_price = 0
            for gift in gifts:
                total_gifts_price += gift.price
                if gift.bought:
                    spent += gift.price
            budget_used += total_gifts_price

        context["persons"] = new_context
        context["budget_total"] = budget_total
        context["budget_used"] = budget_used
        context["spent"] = spent
        print(context)
        return context

    def get_queryset(self):
        return Person.objects.all()


class DetailPerson(generic.UpdateView):
    model = Person
    template_name = "gifts/person_detail.html"

    # success_url = reverse_lazy('gifts:listPersons')
    form_class = inlineformset_factory(Person, Gift, fields=('bought', 'wrapped'), extra=0, can_delete=False)

    def get_success_url(self):
        return reverse_lazy('gifts:detailPerson', kwargs={"pk": self.kwargs["pk"]})

    def get_form(self, form_class=None):
        forms = super().get_form(form_class)
        for form in forms:
            form.fields["bought"].widget.attrs.update(
                {'class': 'bought-widget'})
            form.fields["wrapped"].widget.attrs.update(
                {'class': 'wrapped-widget'})
            if not form.instance.bought:
                form.fields["wrapped"].widget.attrs.update({
                    'disabled': True
                })
        return forms

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        print(form.is_valid())
        print(form)
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AddPerson(generic.CreateView):
    model = Person
    template_name = 'gifts/person_create.html'
    success_url = reverse_lazy('gifts:listPersons')

    fields = [
        'name',
        'budget'
    ]


class DeletePerson(generic.DeleteView):
    model = Person
    success_url = reverse_lazy('gifts:listPersons')


class UpdatePerson(generic.UpdateView):
    model = Person
    template_name = 'gifts/person_update.html'

    fields = [
        'name',
        'budget'
    ]

    def get_success_url(self):
        return reverse_lazy('gifts:detailPerson', kwargs={'pk': self.kwargs["pk"]})


class AddGift(generic.CreateView):
    model = Gift
    context_object_name = 'gift'

    fields = [
        'description',
        'price'
    ]

    def form_valid(self, form):
        print("hello")
        for i in self.request.GET:
            print(i, self.request.GET[i])
        p = get_object_or_404(Person, pk=self.kwargs["person"])
        form.instance.person = p
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('gifts:detailPerson', kwargs={"pk": self.kwargs["person"]})


class UpdateGift(generic.UpdateView):
    model = Gift
    template_name = 'gifts/gift_update.html'

    fields = [
        'description',
        'price'
    ]

    def get_success_url(self):
        return reverse_lazy('gifts:detailPerson', kwargs={"pk": self.object.person.id})


class DeleteGift(generic.DeleteView):
    model = Gift

    def get_success_url(self):
        return reverse_lazy('gifts:detailPerson', kwargs={"pk": self.object.person.id})

gifts/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.9/semantic.min.js"></script>

    <title>Gifts manager</title>
</head>

<body>
    <div class="ui container">
        <div class="ui grid">
            <div class="row">
                <div class="column">
                    <h1>{% block header %}{% endblock %}</h1>
                </div>
            </div>
            <div class="row">
                <div class="column">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <a class="ui button primary" style="margin-top:10px;" href="javascript:history.go(-1);">Back</a>
    </div>
    <script>
        $(function () {
            $('.gifts-progress').progress();
        })
    </script> {% block javascripts %} {% endblock %}
</body>

</html>

gifts/templates/gifts/gift_confirm_delete.html
{% extends 'base.html' %}
{% block header %} Delete - {{object.description}} {% endblock %}


{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="ui button red" type="submit" value="Confirm" />
</form>
{% endblock %}

gifts/templates/gifts/gift_form.html
{% extends 'base.html' %}


{% block header %}Add gift{% endblock %}

{% block content %}
<form action="" method="post" class="ui form">
    {% csrf_token %}
    <div class="field">
        {% if form.description.errors %}
        <div class="ui negative message">
            {{ form.description.errors }}
        </div>
        {% endif %}
        <label for="{{ form.description.id_for_label }}">Description:</label>
        {{ form.description }}
    </div>
    <div class="field">
        {% if form.price.errors %}
        <div class="ui negative message">
            {{ form.price.errors }}
        </div>
        {% endif %}
        <label for="{{ form.price.id_for_label }}">Price:</label>
        {{ form.price }}
    </div>
    <input class="ui button primary" type="submit" value="Create"/>
</form>
{% endblock %}

gifts/templates/gifts/gift_update.html
{% extends 'gifts/gift_form.html' %} {% block header %}Edit gift{% endblock %}

gifts/templates/gifts/person_confirm_delete.html
{% extends 'base.html' %}
{% block header %} Delete - {{person.name}} {% endblock %}


{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="ui button red" type="submit" value="Confirm" />
</form>
{% endblock %}

gifts/templates/gifts/person_confirm_update.html
{% extends 'base.html' %}
{% block header %} Delete - {{object.description}} {% endblock %}


{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to update "{{ object }}"?</p>
    <input class="ui button red" type="submit" value="Confirm" />
</form>
{% endblock %}

gifts/templates/gifts/person_create.html
{% extends 'gifts/person_form.html' %} {% block header %}Create person{% endblock %}

gifts/templates/gifts/person_detail.html
{% extends 'base.html' %} {% block header %} Details - {{person.name}} {% endblock %} {% block content %}
<a class="ui button" href="{% url 'gifts:addGift' person.id %}">Add gift</a>
<a class="ui button primary" href="{% url 'gifts:updatePerson' person.id %}">Edit</a>

{% block javascript %}

<script type="text/javascript">

    function unlockSubmit() {
        $('#updateButton').prop('disabled', false)
    }

    $(function () {
        $('.wrapped-widget').parent().checkbox({
            onChange: function (e) {
                unlockSubmit()
            },
            onUnchecked: function () {
                $this = $(this);
                $tr = $this.closest('tr').removeClass('positive').addClass('warning')
            },
            onChecked: function () {
                $this = $(this);
                $tr = $this.closest('tr').removeClass('warning').addClass('positive')
            }
        });

        $('.bought-widget').parent().checkbox({
            onChange: function (e) {
                unlockSubmit()
            },
            onUnchecked: function (e) {
                $this = $(this);
                $wrappedCB = $this.parent().parent().next().children().children('input');
                $wrappedCB.prop('checked', false);
                $wrappedCB.prop('disabled', true);
                $tr = $this.closest('tr').removeClass('positive').removeClass('warning').addClass('negative')
            },
            onChecked: function () {
                $this = $(this);
                $wrappedCB = $this.parent().parent().next().children().children('input');
                $wrappedCB.prop('disabled', false);
                $tr = $this.closest('tr').removeClass('negative').addClass('warning')
            }
        });
    })
</script> {% endblock %}

<form action="" method="post" class="ui form">
    {% csrf_token %}
    <table class="ui compact celled table">
        <thead>
            <tr>
                <th>Description</th>
                <th>Price</th>
                <th>Bought</th>
                <th>Wrapped</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {{form.management_form}} {% for giftForm in form %} {{giftForm.id}}
            <tr class="{% if not giftForm.bought %}negative{% elif not giftForm.bought %}warning{% else %}positive{% endif %}">
                <td>{{giftForm.instance.description}}</td>
                <td>{{giftForm.instance.price}} $</td>
                <td class="collapsing">
                    <div class="ui fitted toggle checkbox">
                        {{giftForm.bought}}
                    </div>
                </td>
                <td class="collapsing">
                    <div class="ui fitted toggle checkbox">
                        {{giftForm.wrapped}}
                    </div>
                </td>
                <td>
                    <a class="ui button primary" href="{% url 'gifts:updateGift' giftForm.instance.id %}">Edit</a>
                    <a class="ui red button" href="{% url 'gifts:deleteGift' giftForm.instance.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot class="full-width">
            <tr>
                <th></th>
                <th>
                    <div class="ui small">
                        <p>Total : {{ total }} $</p>
                    </div>
                </th>
                <th colspan="4">
                    <input id="updateButton" class="ui button primary right floated" type="submit" value="Update" disabled />
                </th>
            </tr>
        </tfoot>
    </table>
</form>
{% endblock %}

gifts/templates/gifts/person_form.html
{% extends 'base.html' %} {% block header %}Create person{% endblock %} {% block content %}
<form action="" method="post" class="ui form">
    {% csrf_token %}
    <div class="field">
        {% if form.name.errors %}
        <div class="ui negative message">
            {{ form.name.errors }}
        </div>
        {% endif %}
        <label for="{{ form.name.id_for_label }}">Name:</label>
        {{ form.name }}
    </div>
    <div class="field">
        {% if form.budget.errors %}
        <div class="ui negative message">
            {{ form.budget.errors }}
        </div>
        {% endif %}
        <label for="{{ form.budget.id_for_label }}">Budget:</label>
        {{ form.budget }}
    </div>
    <input class="ui button primary" type="submit" value="Create" />
</form>
{% endblock %}

gifts/templates/gifts/person_list.html
{% extends 'base.html' %} {% block header %}Persons list{% endblock %} {% block content %}
<a class="ui button" href="{% url 'gifts:addPerson' %}">Add person</a>
<div class="ui divided items">
    {% for id, person in persons.items %}
    <div class="item">
        <div class="content">
            <a class="header">{{person.instance.name}}</a>
            <div class="meta">
                <span class="price">Budget: {{ person.instance.budget }} $</span>
            </div>
            <p>Bought:</p>
            <div class="ui indicating progress gifts-progress" data-value="{{person.bought}}"
                 data-total="{{person.total}}">
                <div class="bar"></div>
            </div>
            <p>Wrapped:</p>
            <div class="ui indicating progress gifts-progress" data-value="{{person.wrapped}}"
                 data-total="{{person.total}}">
                <div class="bar"></div>
            </div>

            <div class="extra">
                <div class="ui right floated">
                    <a class="ui primary button" href="{% url 'gifts:detailPerson' id %}">Show</a>
                    <a class="ui red button" href="{% url 'gifts:deletePerson' id %}">Delete</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<hr>
<div class="stats">
    <h3>Statistiques</h3>
    <div class="budgets_stats ui horizontal list">
        <div class="item">
            {% load static %}
            <img class="ui avatar image" src="{% static "gifts/budget.png" %}" alt="My image"/>
            <div class="content">
              <div class="header">Budget total</div>
              {{ budget_total }} $
            </div>
        </div>
        <div class="item">
            {% load static %}
            <img class="ui avatar image" src="{% static "gifts/budget.png" %}" alt="My image"/>
            <div class="content">
              <div class="header">Budget used</div>
              {{ budget_used }} $
            </div>
        </div>
        <div class="item">
            {% load static %}
            <img class="ui avatar image" src="{% static "gifts/budget.png" %}" alt="My image"/>
            <div class="content">
              <div class="header">Spent</div>
              {{ spent }} $
            </div>
        </div>
    </div>
</div>
<br/>
{% endblock %}

gifts/templates/gifts/person_update.html
{% extends 'gifts/person_form.html' %} {% block header %}Edit person{% endblock %}